import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Email Authentication',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex justify-center items-center w-full h-screen bg-gray-200">
        {children}
      </body>
    </html>
  );
}
